# This workflow will allows you to deploy to Heroku
# https://github.com/marketplace/actions/deploy-to-heroku

name: Deploy Heroku

on:
  #  push:
  #    branches: [ "main" ]
  #  pull_request:
  #    branches: [ "main" ]
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Heroku Action
        uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "daily-serbian"
          heroku_email: "epifana89@gmail.com"
          buildpack: "heroku/python"
          #            - "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git"
          branch: "main"
          healthcheck: "https://daily-serbian.herokuapp.com/health"
        env:
          HD_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
